export const fullDashboardGoals = [
  {
    "slug": "peso",
    "icon": "⚖️",
    "title": "Quero emagrecer",
    "description": "Perda de peso corporal.",
    "active": true,
    "sort_order": 0
  },
  {
    "slug": "fome",
    "icon": "🍽️",
    "title": "Quero controlar a fome",
    "description": "Saciedade e apetite.",
    "active": true,
    "sort_order": 10
  },
  {
    "slug": "barriga",
    "icon": "🎯",
    "title": "Quero perder barriga",
    "description": "Peso geral, visceral ou localizada.",
    "active": true,
    "sort_order": 20
  },
  {
    "slug": "metabolismo",
    "icon": "🔥",
    "title": "Quero melhorar metabolismo",
    "description": "Insulina, gasto e metabolismo.",
    "active": true,
    "sort_order": 30
  },
  {
    "slug": "gh",
    "icon": "📈",
    "title": "Quero entender GH",
    "description": "GH, IGF-1 e composição corporal.",
    "active": true,
    "sort_order": 40
  },
  {
    "slug": "pele",
    "icon": "✨",
    "title": "Quero pele e colágeno",
    "description": "Reparação e estética.",
    "active": true,
    "sort_order": 50
  },
  {
    "slug": "libido",
    "icon": "❤️",
    "title": "Quero melhorar libido",
    "description": "Desejo sexual.",
    "active": true,
    "sort_order": 60
  },
  {
    "slug": "energia",
    "icon": "⚡",
    "title": "Quero energia celular",
    "description": "Mitocôndria e metabolismo celular.",
    "active": true,
    "sort_order": 70
  },
  {
    "slug": "recuperacao",
    "icon": "🧩",
    "title": "Quero recuperação",
    "description": "Músculo, tendão e tecidos.",
    "active": true,
    "sort_order": 80
  },
  {
    "slug": "cerebro",
    "icon": "🧠",
    "title": "Quero neuroproteção",
    "description": "Pesquisa neurológica.",
    "active": true,
    "sort_order": 90
  },
  {
    "slug": "composicao",
    "icon": "🧪",
    "title": "Quero entender os blends",
    "description": "Blends para estética, pele e recuperação.",
    "active": true,
    "sort_order": 100
  }
] as const;

export const fullDashboardProducts = [
  {
    "slug": "tg15",
    "name": "T.G 15",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "4 ampolas de Tirzepatida 15 mg/0,5 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 0,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "tirzec4",
    "name": "Tirzec 4 Ampolas",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "4 ampolas de Tirzepatida 15 mg/0,5 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 10,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "lipoless4",
    "name": "Lipoless 4 Ampolas",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "Aparece na aba Tirzepatida; o card do print não exibe a concentração textual",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 20,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "tirzegen",
    "name": "Tirzegen",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "60 mg em pó liofilizado + 2 mL de água bacteriostática",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 30,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "tirzec15",
    "name": "Tirzec 15",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "1 frasco multidose com 60 mg de Tirzepatida em 2 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 40,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "lipoless60",
    "name": "Lipoless",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "1 frasco multidose com 60 mg de Tirzepatida em 2,4 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 50,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "gluconex",
    "name": "Gluconex",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "4 ampolas de Tirzepatida 15 mg/1 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 60,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "tirzedral",
    "name": "Tirzedral",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "4 ampolas de Tirzepatida 15 mg/0,5 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 70,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "tirzedralmd",
    "name": "Tirzedral MD",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "60 mg de tirzepatida em ampola única",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 80,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "lipoland",
    "name": "Lipoland",
    "scientific_family": "Tirzepatida",
    "category": "",
    "level": "Evidência clínica forte em obesidade",
    "level_class": "strong",
    "presentation": "1 frasco multidose com 60 mg de Tirzepatida em 2 mL",
    "short_summary": "Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.",
    "pitch": "Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.",
    "studied_for": "Perda de peso corporal, fome/saciedade e saúde metabólica.",
    "research_shows": "No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.",
    "important_note": "As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 90,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo",
      "barriga"
    ]
  },
  {
    "slug": "reta40",
    "name": "Retatrutida 40 mg",
    "scientific_family": "Retatrutida",
    "category": "",
    "level": "Estudos clínicos em humanos",
    "level_class": "human",
    "presentation": "40 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.",
    "pitch": "Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.",
    "studied_for": "Pesquisa de grande perda de peso, saciedade e metabolismo.",
    "research_shows": "Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.",
    "important_note": "40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 100,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo"
    ]
  },
  {
    "slug": "reta40x4",
    "name": "Retatrutida 40 mg — 4 ampolas",
    "scientific_family": "Retatrutida",
    "category": "",
    "level": "Estudos clínicos em humanos",
    "level_class": "human",
    "presentation": "4 ampolas de 40 mg",
    "short_summary": "Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.",
    "pitch": "Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.",
    "studied_for": "Pesquisa de grande perda de peso, saciedade e metabolismo.",
    "research_shows": "Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.",
    "important_note": "40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 110,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo"
    ]
  },
  {
    "slug": "reta80",
    "name": "Retatrutida 80 mg",
    "scientific_family": "Retatrutida",
    "category": "",
    "level": "Estudos clínicos em humanos",
    "level_class": "human",
    "presentation": "80 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.",
    "pitch": "Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.",
    "studied_for": "Pesquisa de grande perda de peso, saciedade e metabolismo.",
    "research_shows": "Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.",
    "important_note": "40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 120,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo"
    ]
  },
  {
    "slug": "reta120",
    "name": "Retatrutida 120 mg",
    "scientific_family": "Retatrutida",
    "category": "",
    "level": "Estudos clínicos em humanos",
    "level_class": "human",
    "presentation": "120 mg",
    "short_summary": "Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.",
    "pitch": "Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.",
    "studied_for": "Pesquisa de grande perda de peso, saciedade e metabolismo.",
    "research_shows": "Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.",
    "important_note": "40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 130,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo"
    ]
  },
  {
    "slug": "reta160",
    "name": "Retatrutida 160 mg",
    "scientific_family": "Retatrutida",
    "category": "",
    "level": "Estudos clínicos em humanos",
    "level_class": "human",
    "presentation": "160 mg",
    "short_summary": "Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.",
    "pitch": "Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.",
    "studied_for": "Pesquisa de grande perda de peso, saciedade e metabolismo.",
    "research_shows": "Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.",
    "important_note": "40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 140,
    "goal_slugs": [
      "peso",
      "fome",
      "metabolismo"
    ]
  },
  {
    "slug": "tesa",
    "name": "Tesamorelin 10 mg",
    "scientific_family": "Tesamorelin",
    "category": "",
    "level": "Evidência humana em contexto específico",
    "level_class": "specific",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Análogo de GHRH que estimula o eixo do hormônio do crescimento e foi estudado especialmente para gordura visceral.",
    "pitch": "Se a pergunta é “quero entender gordura abdominal visceral”, tesamorelin pertence a uma conversa diferente das terapias de saciedade.",
    "studied_for": "Gordura visceral e eixo GH.",
    "research_shows": "Ensaios humanos mostraram redução de gordura visceral em populações específicas, com foco em composição corporal.",
    "important_note": "Não é equivalente a um medicamento de perda de peso geral.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 150,
    "goal_slugs": [
      "barriga",
      "gh"
    ]
  },
  {
    "slug": "ghk100d",
    "name": "GHK-CU 100 mg",
    "scientific_family": "GHK-Cu",
    "category": "",
    "level": "Pesquisa dermatológica / regenerativa",
    "level_class": "specific",
    "presentation": "Já diluído em 2 mL",
    "short_summary": "Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.",
    "pitch": "Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.",
    "studied_for": "Pele, colágeno e regeneração tecidual.",
    "research_shows": "Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.",
    "important_note": "As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 160,
    "goal_slugs": [
      "pele",
      "recuperacao"
    ]
  },
  {
    "slug": "glow",
    "name": "Glow 70 mg",
    "scientific_family": "Blend Glow",
    "category": "",
    "level": "Blend de proposta estética",
    "level_class": "unknown",
    "presentation": "70 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Blend voltado a quem busca suporte para pele, viço, colágeno e reparação, dentro de uma proposta de cuidado estético integrado.",
    "pitch": "Glow costuma ser procurado por quem deseja combinar cuidados com a aparência da pele, luminosidade e suporte à renovação dos tecidos. O racional do blend está associado a vias de colágeno, matriz extracelular e reparação.",
    "studied_for": "Suporte à qualidade da pele, viço, colágeno, renovação e reparação tecidual em protocolos estéticos.",
    "research_shows": "Os mecanismos ligados a colágeno e reparação possuem base pré-clínica e dermatológica, mas o resultado de um blend depende da fórmula, das concentrações e do contexto de uso; a evidência não deve ser extrapolada como garantia estética.",
    "important_note": "Glow é uma linha comercial de blend, não uma promessa de rejuvenescimento. A escolha depende do objetivo, da composição confirmada, do histórico e de orientação responsável; não substitui avaliação profissional.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 170,
    "goal_slugs": [
      "composicao"
    ]
  },
  {
    "slug": "klow",
    "name": "KLOW 80 mg",
    "scientific_family": "Blend KLOW",
    "category": "",
    "level": "Blend de suporte regenerativo",
    "level_class": "unknown",
    "presentation": "80 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Blend voltado a quem busca suporte para recuperação, integridade dos tecidos, pele e equilíbrio de processos inflamatórios ligados ao reparo.",
    "pitch": "KLOW costuma ser procurado em estratégias de recuperação e suporte regenerativo. A proposta reúne mecanismos associados à resposta dos tecidos, manutenção da pele e modulação das etapas envolvidas no reparo.",
    "studied_for": "Recuperação de tecidos, suporte regenerativo, pele e mecanismos relacionados à resposta inflamatória e ao reparo.",
    "research_shows": "Há pesquisa pré-clínica sobre diferentes vias de reparação e inflamação, porém o alcance do blend depende dos ingredientes e concentrações da fórmula comercial. Esses mecanismos não comprovam, por si só, um resultado clínico específico.",
    "important_note": "KLOW deve ser entendido como blend de suporte, e não como tratamento garantido para lesões ou inflamação. A escolha depende do objetivo, histórico, composição confirmada e orientação responsável; não substitui avaliação profissional.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 180,
    "goal_slugs": [
      "composicao"
    ]
  },
  {
    "slug": "pt141",
    "name": "PT-141 10 mg",
    "scientific_family": "PT-141 / Bremelanotida",
    "category": "",
    "level": "Evidência clínica humana",
    "level_class": "strong",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Peptídeo associado a vias de melanocortina, estudado principalmente para desejo sexual reduzido.",
    "pitch": "Se o objetivo é libido, PT-141 é a opção da lista que pertence diretamente a essa conversa.",
    "studied_for": "Desejo sexual, resposta sexual e redução do desconforto associado à baixa libido em contextos específicos.",
    "research_shows": "Ensaios fase 3 mostraram melhora em medidas de desejo sexual e sofrimento relacionado ao baixo desejo em uma população específica.",
    "important_note": "Não é uma terapia de emagrecimento.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 190,
    "goal_slugs": [
      "libido"
    ]
  },
  {
    "slug": "cbl",
    "name": "CBL-514",
    "scientific_family": "CBL-514",
    "category": "",
    "level": "Fase 2 / 2b",
    "level_class": "human",
    "presentation": "Acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Substância injetável em pesquisa para redução de gordura subcutânea localizada.",
    "pitch": "Pense no CBL-514 como uma tecnologia de contorno corporal: a proposta é agir na gordura da região tratada, e não controlar fome.",
    "studied_for": "Gordura localizada e contorno corporal.",
    "research_shows": "Programas fase 2/2b vêm avaliando gordura abdominal localizada em humanos.",
    "important_note": "Gordura localizada e obesidade sistêmica são objetivos diferentes.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 200,
    "goal_slugs": [
      "barriga"
    ]
  },
  {
    "slug": "slu",
    "name": "SLU-PP-33 5 mg",
    "scientific_family": "SLU-PP-33 (nome do catálogo)",
    "category": "",
    "level": "Pesquisa metabólica pré-clínica",
    "level_class": "unknown",
    "presentation": "5 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Opção voltada à pesquisa metabólica, com interesse em gasto energético, uso de substratos e performance celular por mecanismos associados à adaptação ao exercício.",
    "pitch": "SLU-PP-33 costuma ser procurado por quem acompanha pesquisas sobre metabolismo e eficiência energética. A linha relacionada investiga a ativação de programas celulares semelhantes aos acionados pelo exercício, sem equivaler aos benefícios completos da atividade física.",
    "studied_for": "Gasto energético, metabolismo de gordura, capacidade oxidativa e performance metabólica celular.",
    "research_shows": "A literatura disponível para a molécula relacionada SLU-PP-332 é predominantemente pré-clínica e descreve aumento do metabolismo oxidativo e da resistência em modelos animais; ainda faltam dados clínicos robustos em humanos.",
    "important_note": "O nome do catálogo é SLU-PP-33 e não deve ser automaticamente tratado como idêntico ao SLU-PP-332 estudado na literatura. É uma linha experimental, não substitui exercício nem avaliação profissional.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 210,
    "goal_slugs": [
      "metabolismo"
    ]
  },
  {
    "slug": "hgh",
    "name": "HGH FRAG",
    "scientific_family": "HGH Fragment",
    "category": "",
    "level": "Predominantemente experimental",
    "level_class": "experimental",
    "presentation": "Apresentação mostrada no catálogo",
    "short_summary": "Fragmento relacionado ao eixo do hormônio do crescimento, procurado pelo interesse em mobilização de gordura e composição corporal.",
    "pitch": "HGH FRAG costuma ser procurado por quem busca compreender estratégias ligadas ao metabolismo de gordura sem utilizar a molécula completa de GH. Seu racional técnico concentra-se em trechos associados à atividade lipolítica.",
    "studied_for": "Eixo GH, lipólise, metabolismo de gordura e possíveis efeitos sobre composição corporal.",
    "research_shows": "Estudos laboratoriais e pré-clínicos sustentam o interesse em mecanismos lipolíticos, mas a evidência humana para perda de peso relevante permanece limitada e menos consistente que a de terapias aprovadas para obesidade.",
    "important_note": "Atuar em um mecanismo relacionado ao GH não significa reproduzir todos os efeitos do hormônio nem garantir redução de gordura. A escolha depende do objetivo, histórico e orientação responsável; não substitui avaliação profissional.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 220,
    "goal_slugs": [
      "gh",
      "metabolismo"
    ]
  },
  {
    "slug": "semax",
    "name": "SEMAX",
    "scientific_family": "Semax",
    "category": "",
    "level": "Evidência clínica limitada",
    "level_class": "experimental",
    "presentation": "Apresentação mostrada no catálogo",
    "short_summary": "Opção voltada a neuroproteção, foco, cognição e recuperação neurológica, com pesquisa sobre adaptação do sistema nervoso.",
    "pitch": "Semax costuma ser procurado por quem busca suporte para foco e desempenho cognitivo ou acompanha linhas de recuperação neurológica. O racional envolve mecanismos neurotróficos, resposta ao estresse e plasticidade neural.",
    "studied_for": "Neuroproteção, atenção, cognição, adaptação ao estresse e recuperação neurológica em contextos específicos.",
    "research_shows": "Há estudos clínicos pequenos e literatura experimental, especialmente em neurologia e recuperação após eventos cerebrovasculares, mas os dados são heterogêneos e não estabelecem benefício garantido para foco em pessoas saudáveis.",
    "important_note": "Semax não é uma terapia de emagrecimento nem uma solução definitiva para sintomas cognitivos ou neurológicos. A escolha depende do objetivo, histórico e orientação responsável; não substitui avaliação profissional.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 230,
    "goal_slugs": [
      "cerebro"
    ]
  },
  {
    "slug": "aod",
    "name": "AOD 5 mg",
    "scientific_family": "AOD-9604",
    "category": "",
    "level": "Humano limitado / experimental",
    "level_class": "experimental",
    "presentation": "5 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Fragmento modificado relacionado ao GH criado para explorar efeitos sobre metabolismo de gordura.",
    "pitch": "É uma molécula interessante para entender a história dos peptídeos metabólicos: teoria forte, mas resultados humanos menos impressionantes.",
    "studied_for": "Pesquisa de lipólise e metabolismo de gordura.",
    "research_shows": "Estudos pré-clínicos foram positivos; ensaios humanos posteriores não consolidaram uma grande eficácia para emagrecimento.",
    "important_note": "Mecanismo interessante não equivale a grande resultado clínico.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 240,
    "goal_slugs": [
      "metabolismo",
      "gh"
    ]
  },
  {
    "slug": "cjcipa",
    "name": "CJC 1295 + Ipamorelin 10 mg",
    "scientific_family": "CJC-1295 + Ipamorelin",
    "category": "",
    "level": "Farmacologia humana + uso experimental",
    "level_class": "specific",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Combinação que tenta estimular o eixo do hormônio do crescimento por duas vias diferentes.",
    "pitch": "A lógica é simples: CJC e Ipamorelin usam caminhos diferentes para conversar com o mesmo eixo hormonal.",
    "studied_for": "Eixo GH e composição corporal.",
    "research_shows": "CJC-1295 demonstrou elevação de GH/IGF-1 em humanos; isso comprova ação hormonal, não grande perda de peso.",
    "important_note": "Não é equivalente a uma terapia de saciedade.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 250,
    "goal_slugs": [
      "gh"
    ]
  },
  {
    "slug": "ipa",
    "name": "Ipamorelin 10 mg",
    "scientific_family": "Ipamorelin",
    "category": "",
    "level": "Estudos humanos em outras indicações",
    "level_class": "specific",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Secretagogo de GH que atua por via relacionada ao receptor de grelina.",
    "pitch": "Se CJC trabalha uma porta do sistema do GH, Ipamorelin trabalha outra.",
    "studied_for": "Estimulação do eixo GH, liberação pulsátil do hormônio do crescimento e possíveis efeitos em composição corporal e recuperação.",
    "research_shows": "Foi estudado em humanos em outros contextos; a evidência para grande emagrecimento é limitada.",
    "important_note": "Não deve ser confundido com medicamentos de obesidade.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 260,
    "goal_slugs": [
      "gh"
    ]
  },
  {
    "slug": "mots",
    "name": "MOTS-C 10 mg",
    "scientific_family": "MOTS-c",
    "category": "",
    "level": "Pesquisa humana em evolução",
    "level_class": "human",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Peptídeo derivado da mitocôndria investigado por sensibilidade à insulina, energia e homeostase metabólica.",
    "pitch": "Se você olha o peso pela saúde metabólica, MOTS-c é uma molécula especialmente interessante para acompanhar.",
    "studied_for": "Metabolismo, resistência à insulina e mitocôndria.",
    "research_shows": "Pesquisa clínica em adultos com pré-diabetes e sobrepeso/obesidade vem avaliando sensibilidade à insulina.",
    "important_note": "A evidência ainda está sendo construída.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 270,
    "goal_slugs": [
      "metabolismo",
      "energia"
    ]
  },
  {
    "slug": "ss31",
    "name": "SS-31 10 mg",
    "scientific_family": "SS-31 / Elamipretide",
    "category": "",
    "level": "Ensaios humanos",
    "level_class": "human",
    "presentation": "10 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Peptídeo direcionado à função mitocondrial e produção de energia celular.",
    "pitch": "Aqui a conversa é eficiência mitocondrial, não fome ou saciedade.",
    "studied_for": "Mitocôndria e energia celular.",
    "research_shows": "Foi avaliado em ensaios humanos, inclusive estudos maiores, com resultados variáveis conforme a condição estudada.",
    "important_note": "Metabolismo mitocondrial não significa automaticamente emagrecimento.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 280,
    "goal_slugs": [
      "energia"
    ]
  },
  {
    "slug": "tb",
    "name": "TB-500 + BPC-157 20 mg",
    "scientific_family": "TB-500 + BPC-157",
    "category": "",
    "level": "Evidência humana muito limitada",
    "level_class": "experimental",
    "presentation": "20 mg; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Combinação popular em discussões sobre reparação de tecidos, músculo e tendão.",
    "pitch": "Se o interesse é recuperação tecidual, essa combinação aparece muito — mas a ciência humana ainda está atrás da popularidade.",
    "studied_for": "Reparação e recuperação tecidual.",
    "research_shows": "Há muita pesquisa pré-clínica e poucos dados humanos robustos para as alegações mais amplas.",
    "important_note": "Popularidade em biohacking não equivale a eficácia comprovada.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 290,
    "goal_slugs": [
      "recuperacao"
    ]
  },
  {
    "slug": "nad",
    "name": "NAD+ 500 mg",
    "scientific_family": "NAD+",
    "category": "",
    "level": "Pesquisa clínica ainda limitada",
    "level_class": "specific",
    "presentation": "500 mg",
    "short_summary": "Molécula central para centenas de reações ligadas a metabolismo e produção de energia celular.",
    "pitch": "NAD+ é melhor entendido como uma peça central da bioquímica da célula do que como um medicamento de emagrecimento.",
    "studied_for": "Energia celular, metabolismo e pesquisa de longevidade.",
    "research_shows": "Existem estudos humanos sobre metabolismo e administração de NAD+, mas a evidência é menor para muitas promessas comerciais.",
    "important_note": "Participar do metabolismo não significa, por si só, causar perda de peso.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 300,
    "goal_slugs": [
      "energia"
    ]
  },
  {
    "slug": "ghk100po",
    "name": "GHK-CU 100 MG PÓ",
    "scientific_family": "GHK-Cu",
    "category": "",
    "level": "Pesquisa dermatológica / regenerativa",
    "level_class": "specific",
    "presentation": "100 mg em pó; acompanha 1 água bacteriostática de 2 mL",
    "short_summary": "Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.",
    "pitch": "Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.",
    "studied_for": "Pele, colágeno e regeneração tecidual.",
    "research_shows": "Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.",
    "important_note": "As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 310,
    "goal_slugs": [
      "pele",
      "recuperacao"
    ]
  },
  {
    "slug": "ghk50",
    "name": "GHK-CU 50 mg",
    "scientific_family": "GHK-Cu",
    "category": "",
    "level": "Pesquisa dermatológica / regenerativa",
    "level_class": "specific",
    "presentation": "Já diluído ou pó liofilizado com 1 água bacteriostática de 2 mL",
    "short_summary": "Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.",
    "pitch": "Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.",
    "studied_for": "Pele, colágeno e regeneração tecidual.",
    "research_shows": "Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.",
    "important_note": "As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 320,
    "goal_slugs": [
      "pele",
      "recuperacao"
    ]
  },
  {
    "slug": "ghk50lio",
    "name": "GHK-CU 50 MG PÓ LIOFILIZADO",
    "scientific_family": "GHK-Cu",
    "category": "",
    "level": "Pesquisa dermatológica / regenerativa",
    "level_class": "specific",
    "presentation": "50 mg em pó liofilizado + 2 mL de água bacteriostática",
    "short_summary": "Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.",
    "pitch": "Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.",
    "studied_for": "Pele, colágeno e regeneração tecidual.",
    "research_shows": "Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.",
    "important_note": "As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.",
    "image_url": "",
    "buy_url": "",
    "active": true,
    "sort_order": 330,
    "goal_slugs": [
      "pele",
      "recuperacao"
    ]
  }
] as const;
