begin;

-- O seed é autoritativo para o catálogo original: itens legados ficam inativos.
update public.dashboard_goals set active = false, updated_at = now();
update public.dashboard_products set active = false, updated_at = now();

insert into public.dashboard_goals (slug,icon,title,description,active,sort_order) values
('peso','⚖️','Quero emagrecer','Perda de peso corporal.',true,0),
('fome','🍽️','Quero controlar a fome','Saciedade e apetite.',true,10),
('barriga','🎯','Quero perder barriga','Peso geral, visceral ou localizada.',true,20),
('metabolismo','🔥','Quero melhorar metabolismo','Insulina, gasto e metabolismo.',true,30),
('gh','📈','Quero entender GH','GH, IGF-1 e composição corporal.',true,40),
('pele','✨','Quero pele e colágeno','Reparação e estética.',true,50),
('libido','❤️','Quero melhorar libido','Desejo sexual.',true,60),
('energia','⚡','Quero energia celular','Mitocôndria e metabolismo celular.',true,70),
('recuperacao','🧩','Quero recuperação','Músculo, tendão e tecidos.',true,80),
('cerebro','🧠','Quero neuroproteção','Pesquisa neurológica.',true,90),
('composicao','🧪','Quero entender os blends','Glow e KLOW precisam da fórmula.',true,100)
on conflict (slug) do update set icon=excluded.icon,title=excluded.title,description=excluded.description,active=true,sort_order=excluded.sort_order,updated_at=now();

insert into public.dashboard_products (slug,name,scientific_family,category,level,level_class,presentation,short_summary,pitch,studied_for,research_shows,important_note,image_url,buy_url,active,sort_order) values
('tg15','T.G 15','Tirzepatida','','Evidência clínica forte em obesidade','strong','4 ampolas de Tirzepatida 15 mg/0,5 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,0),
('tirzec4','Tirzec 4 Ampolas','Tirzepatida','','Evidência clínica forte em obesidade','strong','4 ampolas de Tirzepatida 15 mg/0,5 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,10),
('lipoless4','Lipoless 4 Ampolas','Tirzepatida','','Evidência clínica forte em obesidade','strong','Aparece na aba Tirzepatida; o card do print não exibe a concentração textual','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,20),
('tirzegen','Tirzegen','Tirzepatida','','Evidência clínica forte em obesidade','strong','60 mg em pó liofilizado + 2 mL de água bacteriostática','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,30),
('tirzec15','Tirzec 15','Tirzepatida','','Evidência clínica forte em obesidade','strong','1 frasco multidose com 60 mg de Tirzepatida em 2 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,40),
('lipoless60','Lipoless','Tirzepatida','','Evidência clínica forte em obesidade','strong','1 frasco multidose com 60 mg de Tirzepatida em 2,4 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,50),
('gluconex','Gluconex','Tirzepatida','','Evidência clínica forte em obesidade','strong','4 ampolas de Tirzepatida 15 mg/1 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,60),
('tirzedral','Tirzedral','Tirzepatida','','Evidência clínica forte em obesidade','strong','4 ampolas de Tirzepatida 15 mg/0,5 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,70),
('tirzedralmd','Tirzedral MD','Tirzepatida','','Evidência clínica forte em obesidade','strong','60 mg de tirzepatida em ampola única','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,80),
('lipoland','Lipoland','Tirzepatida','','Evidência clínica forte em obesidade','strong','1 frasco multidose com 60 mg de Tirzepatida em 2 mL','Atua em GIP + GLP-1 e é uma das substâncias com maior evidência humana da lista para perda de peso, redução de apetite e melhora metabólica.','Se seu objetivo principal é perder peso e controlar melhor a fome, esta é a primeira família que vale entender. Ela trabalha saciedade e ingestão de alimentos, e não simplesmente “queima de gordura”.','Perda de peso corporal, fome/saciedade e saúde metabólica.','No SURMOUNT-1, com 2.539 adultos, a redução média de peso em 72 semanas chegou a aproximadamente 15,0%, 19,5% e 20,9% nos grupos de doses estudadas.','As diferentes caixas do catálogo são apresentações/marcas distintas, mas o princípio ativo declarado é tirzepatida. Quantidade total na caixa ou no frasco não é sinônimo de dose individual.','', '',true,90),
('reta40','Retatrutida 40 mg','Retatrutida','','Estudos clínicos em humanos','human','40 mg; acompanha 1 água bacteriostática de 2 mL','Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.','Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.','Pesquisa de grande perda de peso, saciedade e metabolismo.','Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.','40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.','', '',true,100),
('reta40x4','Retatrutida 40 mg — 4 ampolas','Retatrutida','','Estudos clínicos em humanos','human','4 ampolas de 40 mg','Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.','Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.','Pesquisa de grande perda de peso, saciedade e metabolismo.','Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.','40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.','', '',true,110),
('reta80','Retatrutida 80 mg','Retatrutida','','Estudos clínicos em humanos','human','80 mg; acompanha 1 água bacteriostática de 2 mL','Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.','Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.','Pesquisa de grande perda de peso, saciedade e metabolismo.','Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.','40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.','', '',true,120),
('reta120','Retatrutida 120 mg','Retatrutida','','Estudos clínicos em humanos','human','120 mg','Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.','Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.','Pesquisa de grande perda de peso, saciedade e metabolismo.','Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.','40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.','', '',true,130),
('reta160','Retatrutida 160 mg','Retatrutida','','Estudos clínicos em humanos','human','160 mg','Agonista triplo GIP + GLP-1 + glucagon estudado como uma nova geração para obesidade e metabolismo.','Se tirzepatida representa uma das grandes referências atuais, retatrutida é uma das moléculas mais interessantes da próxima geração.','Pesquisa de grande perda de peso, saciedade e metabolismo.','Em fase 2 com 338 adultos, a redução média de peso chegou a 24,2% em 48 semanas no grupo de maior dose estudada.','40, 80, 120 e 160 mg são apresentações do catálogo; não representam quatro moléculas diferentes nem devem ser lidos como uma dose recomendada.','', '',true,140),
('tesa','Tesamorelin 10 mg','Tesamorelin','','Evidência humana em contexto específico','specific','10 mg; acompanha 1 água bacteriostática de 2 mL','Análogo de GHRH que estimula o eixo do hormônio do crescimento e foi estudado especialmente para gordura visceral.','Se a pergunta é “quero entender gordura abdominal visceral”, tesamorelin pertence a uma conversa diferente das terapias de saciedade.','Gordura visceral e eixo GH.','Ensaios humanos mostraram redução de gordura visceral em populações específicas, com foco em composição corporal.','Não é equivalente a um medicamento de perda de peso geral.','', '',true,150),
('ghk100d','GHK-CU 100 mg','GHK-Cu','','Pesquisa dermatológica / regenerativa','specific','Já diluído em 2 mL','Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.','Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.','Pele, colágeno e regeneração tecidual.','Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.','As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.','', '',true,160),
('glow','Glow 70 mg','Blend Glow','','Composição não informada no print','unknown','70 mg; acompanha 1 água bacteriostática de 2 mL','Glow é um nome comercial de blend; o print não mostra os componentes da mistura.','Para explicar Glow corretamente, precisamos primeiro da fórmula. O nome comercial sozinho não permite ligar o produto a estudos específicos.','A definir após conhecer a composição completa.','Sem a composição, não é possível atribuir evidência de uma molécula específica.','Não vou preencher essa lacuna com suposição.','', '',true,170),
('klow','KLOW 80 mg','Blend KLOW','','Composição não informada no print','unknown','80 mg; acompanha 1 água bacteriostática de 2 mL','KLOW é um nome comercial de blend; o print não mostra os componentes da mistura.','Para explicar KLOW corretamente, precisamos primeiro da fórmula. Depois o dashboard pode decompor ingrediente por ingrediente.','A definir após conhecer a composição completa.','Sem a composição, não é possível relacionar o produto a estudos específicos.','Não vou atribuir benefícios sem a fórmula.','', '',true,180),
('pt141','PT-141 10 mg','PT-141 / Bremelanotida','','Evidência clínica humana','strong','10 mg; acompanha 1 água bacteriostática de 2 mL','Peptídeo associado a vias de melanocortina, estudado principalmente para desejo sexual reduzido.','Se o objetivo é libido, PT-141 é a opção da lista que pertence diretamente a essa conversa.','Libido e desejo sexual.','Ensaios fase 3 mostraram melhora em medidas de desejo sexual e sofrimento relacionado ao baixo desejo em uma população específica.','Não é uma terapia de emagrecimento.','', '',true,190),
('cbl','CBL-514','CBL-514','','Fase 2 / 2b','human','Acompanha 1 água bacteriostática de 2 mL','Substância injetável em pesquisa para redução de gordura subcutânea localizada.','Pense no CBL-514 como uma tecnologia de contorno corporal: a proposta é agir na gordura da região tratada, e não controlar fome.','Gordura localizada e contorno corporal.','Programas fase 2/2b vêm avaliando gordura abdominal localizada em humanos.','Gordura localizada e obesidade sistêmica são objetivos diferentes.','', '',true,200),
('slu','SLU-PP-33 5 mg','SLU-PP-33 (nome do catálogo)','','Identidade científica a confirmar','unknown','5 mg; acompanha 1 água bacteriostática de 2 mL','O catálogo mostra “SLU-PP-33 5 mg”. A literatura discutida anteriormente costuma se referir a SLU-PP-332, portanto a correspondência exata precisa ser confirmada.','A família de pesquisa relacionada ficou conhecida pelo conceito de mimético do exercício e gasto energético, mas não é correto atribuir automaticamente esses estudos sem confirmar a molécula do produto.','Pesquisa metabólica — após confirmação da identidade.','Há resultados pré-clínicos interessantes para SLU-PP-332 em metabolismo e gasto energético.','Mantive exatamente o nome mostrado no print para não corrigir silenciosamente o catálogo.','', '',true,210),
('hgh','HGH FRAG','HGH Fragment','','Predominantemente experimental','experimental','Apresentação mostrada no catálogo','Fragmentos de GH são estudados pelo interesse em mecanismos do hormônio do crescimento relacionados ao metabolismo de gordura.','A ideia é tentar explorar a parte do GH ligada à mobilização de gordura sem usar a molécula inteira.','Eixo GH e metabolismo de gordura.','A base mais convincente é pré-clínica; a evidência de grande emagrecimento em humanos é muito menor.','Não se compara em força de evidência às terapias modernas de obesidade.','', '',true,220),
('semax','SEMAX','Semax','','Evidência clínica limitada','experimental','Apresentação mostrada no catálogo','Peptídeo estudado principalmente em neurologia, neuroproteção e recuperação neurológica.','Semax pertence ao universo neurológico da biblioteca, não ao de emagrecimento.','Neuroproteção e pesquisa neurológica.','Existem estudos clínicos menores, sobretudo em recuperação após AVC.','Não é uma solução de controle de peso.','', '',true,230),
('aod','AOD 5 mg','AOD-9604','','Humano limitado / experimental','experimental','5 mg; acompanha 1 água bacteriostática de 2 mL','Fragmento modificado relacionado ao GH criado para explorar efeitos sobre metabolismo de gordura.','É uma molécula interessante para entender a história dos peptídeos metabólicos: teoria forte, mas resultados humanos menos impressionantes.','Pesquisa de lipólise e metabolismo de gordura.','Estudos pré-clínicos foram positivos; ensaios humanos posteriores não consolidaram uma grande eficácia para emagrecimento.','Mecanismo interessante não equivale a grande resultado clínico.','', '',true,240),
('cjcipa','CJC 1295 + Ipamorelin 10 mg','CJC-1295 + Ipamorelin','','Farmacologia humana + uso experimental','specific','10 mg; acompanha 1 água bacteriostática de 2 mL','Combinação que tenta estimular o eixo do hormônio do crescimento por duas vias diferentes.','A lógica é simples: CJC e Ipamorelin usam caminhos diferentes para conversar com o mesmo eixo hormonal.','Eixo GH e composição corporal.','CJC-1295 demonstrou elevação de GH/IGF-1 em humanos; isso comprova ação hormonal, não grande perda de peso.','Não é equivalente a uma terapia de saciedade.','', '',true,250),
('ipa','Ipamorelin 10 mg','Ipamorelin','','Estudos humanos em outras indicações','specific','10 mg; acompanha 1 água bacteriostática de 2 mL','Secretagogo de GH que atua por via relacionada ao receptor de grelina.','Se CJC trabalha uma porta do sistema do GH, Ipamorelin trabalha outra.','Estudo do eixo GH.','Foi estudado em humanos em outros contextos; a evidência para grande emagrecimento é limitada.','Não deve ser confundido com medicamentos de obesidade.','', '',true,260),
('mots','MOTS-C 10 mg','MOTS-c','','Pesquisa humana em evolução','human','10 mg; acompanha 1 água bacteriostática de 2 mL','Peptídeo derivado da mitocôndria investigado por sensibilidade à insulina, energia e homeostase metabólica.','Se você olha o peso pela saúde metabólica, MOTS-c é uma molécula especialmente interessante para acompanhar.','Metabolismo, resistência à insulina e mitocôndria.','Pesquisa clínica em adultos com pré-diabetes e sobrepeso/obesidade vem avaliando sensibilidade à insulina.','A evidência ainda está sendo construída.','', '',true,270),
('ss31','SS-31 10 mg','SS-31 / Elamipretide','','Ensaios humanos','human','10 mg; acompanha 1 água bacteriostática de 2 mL','Peptídeo direcionado à função mitocondrial e produção de energia celular.','Aqui a conversa é eficiência mitocondrial, não fome ou saciedade.','Mitocôndria e energia celular.','Foi avaliado em ensaios humanos, inclusive estudos maiores, com resultados variáveis conforme a condição estudada.','Metabolismo mitocondrial não significa automaticamente emagrecimento.','', '',true,280),
('tb','TB-500 + BPC-157 20 mg','TB-500 + BPC-157','','Evidência humana muito limitada','experimental','20 mg; acompanha 1 água bacteriostática de 2 mL','Combinação popular em discussões sobre reparação de tecidos, músculo e tendão.','Se o interesse é recuperação tecidual, essa combinação aparece muito — mas a ciência humana ainda está atrás da popularidade.','Reparação e recuperação tecidual.','Há muita pesquisa pré-clínica e poucos dados humanos robustos para as alegações mais amplas.','Popularidade em biohacking não equivale a eficácia comprovada.','', '',true,290),
('nad','NAD+ 500 mg','NAD+','','Pesquisa clínica ainda limitada','specific','500 mg','Molécula central para centenas de reações ligadas a metabolismo e produção de energia celular.','NAD+ é melhor entendido como uma peça central da bioquímica da célula do que como um medicamento de emagrecimento.','Energia celular, metabolismo e pesquisa de longevidade.','Existem estudos humanos sobre metabolismo e administração de NAD+, mas a evidência é menor para muitas promessas comerciais.','Participar do metabolismo não significa, por si só, causar perda de peso.','', '',true,300),
('ghk100po','GHK-CU 100 MG PÓ','GHK-Cu','','Pesquisa dermatológica / regenerativa','specific','100 mg em pó; acompanha 1 água bacteriostática de 2 mL','Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.','Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.','Pele, colágeno e regeneração tecidual.','Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.','As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.','', '',true,310),
('ghk50','GHK-CU 50 mg','GHK-Cu','','Pesquisa dermatológica / regenerativa','specific','Já diluído ou pó liofilizado com 1 água bacteriostática de 2 mL','Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.','Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.','Pele, colágeno e regeneração tecidual.','Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.','As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.','', '',true,320),
('ghk50lio','GHK-CU 50 MG PÓ LIOFILIZADO','GHK-Cu','','Pesquisa dermatológica / regenerativa','specific','50 mg em pó liofilizado + 2 mL de água bacteriostática','Peptídeo ligado ao cobre pesquisado por mecanismos relacionados a fibroblastos, colágeno, matriz extracelular e reparação.','Se o objetivo é pele, colágeno ou reparação, GHK-Cu é a família do catálogo mais diretamente ligada a essa conversa.','Pele, colágeno e regeneração tecidual.','Há boa base laboratorial sobre reparação e matriz extracelular; a evidência clínica estética é menor e mais heterogênea.','As quatro caixas do catálogo diferem na quantidade e na forma de apresentação; o componente central continua sendo GHK-Cu.','', '',true,330)
on conflict (slug) do update set name=excluded.name,scientific_family=excluded.scientific_family,category=excluded.category,level=excluded.level,level_class=excluded.level_class,presentation=excluded.presentation,short_summary=excluded.short_summary,pitch=excluded.pitch,studied_for=excluded.studied_for,research_shows=excluded.research_shows,important_note=excluded.important_note,active=true,sort_order=excluded.sort_order,updated_at=now();

-- Preserva URLs já preenchidas no admin e recria integralmente os vínculos.
delete from public.dashboard_product_goals;
insert into public.dashboard_product_goals (product_id,goal_id)
select p.id,g.id from (values
('tg15','peso'),
('tg15','fome'),
('tg15','metabolismo'),
('tg15','barriga'),
('tirzec4','peso'),
('tirzec4','fome'),
('tirzec4','metabolismo'),
('tirzec4','barriga'),
('lipoless4','peso'),
('lipoless4','fome'),
('lipoless4','metabolismo'),
('lipoless4','barriga'),
('tirzegen','peso'),
('tirzegen','fome'),
('tirzegen','metabolismo'),
('tirzegen','barriga'),
('tirzec15','peso'),
('tirzec15','fome'),
('tirzec15','metabolismo'),
('tirzec15','barriga'),
('lipoless60','peso'),
('lipoless60','fome'),
('lipoless60','metabolismo'),
('lipoless60','barriga'),
('gluconex','peso'),
('gluconex','fome'),
('gluconex','metabolismo'),
('gluconex','barriga'),
('tirzedral','peso'),
('tirzedral','fome'),
('tirzedral','metabolismo'),
('tirzedral','barriga'),
('tirzedralmd','peso'),
('tirzedralmd','fome'),
('tirzedralmd','metabolismo'),
('tirzedralmd','barriga'),
('lipoland','peso'),
('lipoland','fome'),
('lipoland','metabolismo'),
('lipoland','barriga'),
('reta40','peso'),
('reta40','fome'),
('reta40','metabolismo'),
('reta40x4','peso'),
('reta40x4','fome'),
('reta40x4','metabolismo'),
('reta80','peso'),
('reta80','fome'),
('reta80','metabolismo'),
('reta120','peso'),
('reta120','fome'),
('reta120','metabolismo'),
('reta160','peso'),
('reta160','fome'),
('reta160','metabolismo'),
('tesa','barriga'),
('tesa','gh'),
('ghk100d','pele'),
('ghk100d','recuperacao'),
('glow','composicao'),
('klow','composicao'),
('pt141','libido'),
('cbl','barriga'),
('slu','metabolismo'),
('hgh','gh'),
('hgh','metabolismo'),
('semax','cerebro'),
('aod','metabolismo'),
('aod','gh'),
('cjcipa','gh'),
('ipa','gh'),
('mots','metabolismo'),
('mots','energia'),
('ss31','energia'),
('tb','recuperacao'),
('nad','energia'),
('ghk100po','pele'),
('ghk100po','recuperacao'),
('ghk50','pele'),
('ghk50','recuperacao'),
('ghk50lio','pele'),
('ghk50lio','recuperacao')
) as rel(product_slug,goal_slug)
join public.dashboard_products p on p.slug=rel.product_slug
join public.dashboard_goals g on g.slug=rel.goal_slug
on conflict (product_id,goal_id) do nothing;

commit;

-- Conferência esperada após o seed: 11 objetivos e 34 produtos ativos.

