begin;
insert into public.dashboard_settings(key,title,subtitle,hero_text,support_text,audit_text,active) values('main','Encontre opções para o seu objetivo','Dashboard de tratamentos e produtos','Explore as alternativas de forma simples, compare linhas de pesquisa e entenda cada opção antes de decidir.','Conteúdo educativo. A indicação e o acompanhamento devem ser feitos por profissional habilitado.','Catálogo revisado pela equipe eLeve Saúde',true) on conflict(key) do update set title=excluded.title,subtitle=excluded.subtitle,hero_text=excluded.hero_text,support_text=excluded.support_text,audit_text=excluded.audit_text;
insert into public.dashboard_goals(slug,icon,title,description,sort_order) values ('emagrecimento','↘','Emagrecimento','Saciedade, metabolismo e controle de peso.',0),('massa-magra','◆','Massa magra','Composição corporal e desempenho.',10),('longevidade','∞','Longevidade','Linhas estudadas em saúde e envelhecimento.',20),('recuperacao','＋','Recuperação','Recuperação, tecidos e bem-estar.',30) on conflict(slug) do nothing;
insert into public.dashboard_products(slug,name,scientific_family,category,level,presentation,short_summary,pitch,studied_for,research_shows,important_note,sort_order) values
('tirzepatida','Tirzepatida','Agonistas GIP/GLP-1','Controle metabólico','Avançado','Conforme orientação profissional','Opção estudada para controle glicêmico, saciedade e manejo crônico do peso.','Uma abordagem de ação dupla para objetivos metabólicos.','Diabetes tipo 2, obesidade e controle crônico do peso.','Estudos clínicos avaliam seus efeitos sobre glicemia, apetite e redução de peso.','Princípio ativo e marca comercial não são a mesma coisa. Exige avaliação e prescrição.',0),
('semaglutida','Semaglutida','Agonistas GLP-1','Controle metabólico','Consolidado','Conforme orientação profissional','Molécula pesquisada em diabetes tipo 2 e manejo do peso.','Uma das linhas GLP-1 mais conhecidas.','Controle glicêmico, saciedade e controle crônico do peso.','A literatura clínica avalia diferentes doses e indicações conforme a apresentação.','Ozempic e Wegovy são marcas com indicações e apresentações próprias.',10),
('retatrutida','Retatrutida','Agonistas GIP/GLP-1/glucagon','Pesquisa metabólica','Experimental','Em investigação clínica','Molécula investigacional de ação tripla em estudos metabólicos.','Uma frente promissora, ainda experimental.','Obesidade e alterações metabólicas em protocolos de pesquisa.','Resultados preliminares motivam estudos maiores e acompanhamento de segurança.','Não confundir pesquisa clínica com aprovação para comercialização ou uso rotineiro.',20),
('tesamorelina','Tesamorelina','Análogos de GHRH','Composição corporal','Especializado','Conforme avaliação clínica','Peptídeo estudado em contextos específicos de composição corporal.','Pesquisa direcionada à composição corporal.','Alterações específicas de gordura visceral e eixo de hormônio do crescimento.','As evidências são ligadas a populações e indicações específicas.','Não é uma alternativa genérica para emagrecimento e requer avaliação especializada.',30),
('bpc-157','BPC-157','Peptídeos derivados gástricos','Pesquisa regenerativa','Experimental','Pesquisa','Composto experimental popular em discussões sobre recuperação de tecidos.','Uma linha de investigação pré-clínica.','Mecanismos de reparo e recuperação em modelos experimentais.','Grande parte das evidências disponíveis ainda é pré-clínica.','Não possui evidência clínica robusta nem aprovação para uso terapêutico rotineiro.',40),
('nad-mais','NAD+','Coenzimas celulares','Longevidade','Em estudo','Protocolos variáveis','Coenzima associada ao metabolismo energético celular.','Metabolismo celular sob uma lente de longevidade.','Energia celular, envelhecimento e metabolismo.','Há interesse científico, mas benefícios clínicos dependem da via e do contexto.','Promessas de rejuvenescimento excedem as evidências atuais.',50) on conflict(slug) do nothing;
insert into public.dashboard_product_goals(product_id,goal_id) select p.id,g.id from (values('tirzepatida','emagrecimento'),('semaglutida','emagrecimento'),('retatrutida','emagrecimento'),('tesamorelina','massa-magra'),('bpc-157','recuperacao'),('nad-mais','longevidade')) as x(product_slug,goal_slug) join public.dashboard_products p on p.slug=x.product_slug join public.dashboard_goals g on g.slug=x.goal_slug on conflict do nothing;
insert into public.dashboard_questions(question,answer,category,sort_order) values('Como escolher uma opção?','Comece pelo objetivo e leve seu histórico a um profissional habilitado. Procedência, indicação, conservação e acompanhamento importam.','Escolha',0),('Todos os produtos estão disponíveis para compra?','Não. Quando não houver um link configurado, o card será sinalizado como Em breve.','Compra',10),('Este dashboard substitui uma consulta?','Não. Ele organiza informação educativa e não oferece diagnóstico, prescrição ou recomendação individual.','Segurança',20);
commit;
