import { BrandLogo } from "@/components/brand/BrandLogo";
import type { GuidePage,GuideSection } from "@/lib/guide-content";
import Image from "next/image";
import Link from "next/link";
import { isSafeContentUrl } from "@/lib/content-validation";
const strings=(value:unknown)=>Array.isArray(value)?value.filter((x):x is string=>typeof x==="string"):[];
const value=(content:Record<string,unknown>,key:string)=>typeof content[key]==="string"?content[key] as string:"";
function SafeLink({href,children}:{href:string;children:React.ReactNode}){const safe=isSafeContentUrl(href)&&href?href:"/isabela";return <Link href={safe} className="inline-flex rounded-full bg-[#047857] px-5 py-3 font-bold text-white">{children}</Link>}
function Block({section}:{section:GuideSection}){const c=section.content,title=value(c,"title"),body=value(c,"body");if(section.section_type==="hero")return <section className="px-5 py-20"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-widest text-[#047857]">{value(c,"eyebrow")}</p><h1 className="mt-4 max-w-4xl font-serif text-5xl font-semibold">{title}</h1><h2 className="mt-5 text-xl font-bold">{value(c,"subtitle")}</h2><p className="mt-5 max-w-3xl leading-7 text-[#344563]">{body}</p>{value(c,"ctaText")&&<div className="mt-7"><SafeLink href={value(c,"ctaUrl")}>{value(c,"ctaText")}</SafeLink></div>}</div></section>;
if(section.section_type==="image")return value(c,"imageUrl")?<figure className="mx-auto max-w-6xl px-5 py-8"><Image src={value(c,"imageUrl")} alt={value(c,"imageAlt")} width={1200} height={600} className="h-auto w-full rounded-[28px] object-cover"/><figcaption className="mt-2 text-sm text-[#344563]">{value(c,"caption")}</figcaption></figure>:null;
if(section.section_type==="faq"){const items=Array.isArray(c.items)?c.items:[];return <section className="bg-[#EEF7F2] px-5 py-16"><div className="mx-auto max-w-6xl"><h2 className="font-serif text-4xl font-semibold">{title}</h2><div className="mt-7 space-y-3">{items.map((raw,index)=>{const item=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};return <details className="rounded-2xl bg-white p-5" key={index}><summary className="font-bold">{value(item,"title")}</summary><p className="mt-3 text-[#344563]">{value(item,"text")}</p></details>})}</div></div></section>}
if(section.section_type==="cta")return <section className="bg-[#0D1B2A] px-5 py-16 text-center text-white"><h2 className="font-serif text-4xl font-semibold">{title}</h2><p className="mx-auto mt-4 max-w-2xl text-white/75">{body}</p><div className="mt-7"><SafeLink href={value(c,"ctaUrl")}>{value(c,"ctaText")}</SafeLink></div></section>;
const items=strings(c.items);return <section className="px-5 py-16"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-widest text-[#047857]">{value(c,"eyebrow")}</p><h2 className="mt-2 font-serif text-4xl font-semibold">{title}</h2>{strings(c.paragraphs).map((p,i)=><p key={i} className="mt-4 max-w-4xl leading-7 text-[#344563]">{p}</p>)}{body&&<blockquote className="mt-6 rounded-2xl bg-[#0D1B2A] p-6 text-xl font-bold text-white">{body}</blockquote>}{items.length>0&&<ul className="mt-7 grid gap-3 sm:grid-cols-2">{items.map((item,i)=><li className="rounded-2xl border bg-white p-5 font-semibold" key={i}>{item}</li>)}</ul>}</div></section>}
export function StructuredGuide({page}:{page:GuidePage}){return <main className="min-h-screen bg-[#FAFAF7] text-[#0D1B2A]"><header className="border-b bg-white px-5 py-4"><div className="mx-auto flex max-w-6xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><BrandLogo size="small"/><div className="max-w-2xl sm:text-right"><p className="font-semibold">{page.title}</p>{page.description&&<p className="mt-1 text-sm text-[#344563]">{page.description}</p>}</div></div></header>{page.sections.filter(x=>x.active).map((section,index)=><Block key={section.id??index} section={section}/>)}</main>}
